services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    env_file: devcontainer.env

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: devcontainer.env

volumes:
  postgres-data: